controller_manager:
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gravity_compensation_controller:
      type: gravity_compensation_controller/GravityCompensationController

joint_state_broadcaster:
  ros__parameters:        
    joints:
      - revolute_1
      - revolute_2
      - revolute_3
    interfaces:
      - position
      - velocity
      - effort

gravity_compensation_controller:
  ros__parameters:        
    joints:
      - revolute_1
      - revolute_2
      - revolute_3
    interfaces:
      - position
      - velocity
      - effort
