controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters:        
    joints:
      - revolute_1
      - revolute_2
      - revolute_3
    interfaces:
      - position
      - velocity
      - effort

velocity_controller:
  ros__parameters:        
    joints:
      - revolute_1
      - revolute_2
      - revolute_3
    interfaces:
      - position
      - velocity
      - effort

