controller_manager:
  ros__parameters:
    update_rate: 500
    thread_priority: 80

    left_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_admittance_controller:
      type: admittance_controller/AdmittanceController

left_joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_revolute_1
      - left_revolute_2
      - left_revolute_3
    interfaces:
      - position
      - velocity
      - effort
    use_local_topics: true

left_admittance_controller:
  ros__parameters:
    joints:
      - left_revolute_1
      - left_revolute_2
      - left_revolute_3
    dynamics_backend: pinocchio
    urdf_path: ""
    dynamics_urdf_filename: exo_dynamics_left.urdf
    reference_trajectory_topic: /left/reference_trajectory
    kp: 50.0
    kd: 5.0
    md: 1.0
    bd: 10.0
    kd_adm: 0.0
    ext_torque_topic: /left/ext_torque
    publish_telemetry: true
    telemetry_topic: /left/admittance_controller/telemetry
    logging_session_topic: /left/admittance_controller/logging/session
    imu_topic: /left/imu
