#!/usr/bin/env python3
"""Launcher for Teensy single-motor serial RTT benchmark.
 use: sudo chrt -f 80 bash -c "source /opt/ros/jazzy/setup.bash && source /home/farid/tesis/exo_right_arm_ws/install/setup.bash && ros2 run exo_utils exo_teensy_serial_rtt --port /dev/teensy_motor --n-motors 3 --cmd-type 1 --samples 1000 --pause-ms 2"
"""

import sys

from exo_utils.teensy_serial_rtt import main


if __name__ == "__main__":
    sys.exit(main())
