#!/usr/bin/env python3
"""Launcher for exo_data_logger (avoids setuptools console_scripts importlib.metadata issues with colcon --symlink-install)."""

import sys

from exo_bringup.data_logger_node import main


if __name__ == '__main__':
    main()
    sys.exit(0)
