#!/usr/bin/env python3
"""Launcher for exo_plot_run (avoids setuptools console_scripts importlib.metadata issues with colcon --symlink-install)."""

import sys

from exo_bringup.plot_run import main


if __name__ == '__main__':
    main()
    sys.exit(0)
